### ISSUE TITLE
esp32-S3 error code 7

### ISSUE THREAD

**Issue by SergePD** [htmltiger/dhtESP32-rmt#2]
v 1.0 not working with esp32s3 (core 2.014) (rmt initialization error, constantly rebooting)
v 2.0, core 3.0.1 - works OK

Cannot use core 3.0.1 - other major issues with display driver.

**Comment by junkfix** [comment]
I dont have S3 to test but which channels are you using in 1.x?
have you tried just the example code only on 1.x?
```
ESP32-S3, the RMT is different, in that channels 0-3 are TX only, and 4-7 are RX only
```
https://www.esp32.com/viewtopic.php?t=33632

**Comment by SergePD** [comment]
I used them all, from 0 to 7. Nothing works.
But core 3.0.1 works (no need to assign a channel in this core)

**Comment by junkfix** [comment]
rmt api has been changed so i had to rewrite whole code in 2.0, i suggest you to look for updated display driver.
